# =================================
# = Spring
# =================================
spring:
  datasource:
    url: jdbc:mysql://realmeet-db.cgnd7u8pvqwu.us-east-2.rds.amazonaws.com:3306/realmeet?&serverTimezone=UTC&useSSL=false
    username: admin